apiVersion: v1
kind: Namespace
metadata:
  name: npu-feature-discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: npu-feature-discovery
  name: furiosa-npu-labeller
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: furiosa-npu-labeller
  namespace: npu-feature-discovery
spec:
  selector:
    matchLabels:
      name: furiosa-npu-labeller
  template:
    metadata:
      annotations:
        priorityClassName: ""
      labels:
        name: furiosa-npu-labeller
    spec:
      serviceAccountName: furiosa-npu-labeller
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      imagePullSecrets:
        - name: ecr-docker-login
      containers:
      - image: ghcr.io/furiosa-ai/furiosa-feature-discovery:latest
        name: furiosa-feature-discovery
        imagePullPolicy: IfNotPresent
        workingDir: /opt/bin
        command: ["./furiosa-feature-discovery"]
        args: [
          # Default interval is 60 secs
          "--interval", "60"
        ]
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: RUST_LOG
            value: "info"
        securityContext:
          privileged: true #Needed for /dev
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: sys
            mountPath: /sys
          - name: dev
            mountPath: /dev
          - name: features-d
            mountPath: "/etc/kubernetes/node-feature-discovery/features.d/"
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
        - name: features-d
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d/"
      nodeSelector:
        kubernetes.io/os: linux
