daemonSet:
  priorityClassName: system-node-critical
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  # add toleration as needed
  # tolerations:
  #   - key: furiosa.ai/npu
  #     operator: Exists
  # add affinity as needed
  # affinity:
  #  nodeAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #        - matchExpressions:
  #            - key: feature.node.kubernetes.io/pci-1ed2.present
  #              operator: In
  #              values:
  #                - "true"
  image:
    repository: registry.corp.furiosa.ai/furiosa/furiosa-feature-discovery
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    cpu: 100m
    memory: 64Mi
  args:
    interval: "60"

node-feature-discovery:
  enabled: true
