name: Build & Test Rust Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-24.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create token via GitHub App
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: 2157275
          private-key: ${{ secrets.CLOUD_NATIVE_WG_CI_GH_APP_PRIVKEY }}
          repositories: |
            furiosa-smi
            furiosa-smi-rs

      - name: Checkout `furiosa-smi`
        uses: actions/checkout@v4
        with:
          repository: furiosa-ai/furiosa-smi
          token: '${{ steps.app-token.outputs.token }}'
          path: furiosa-smi

      - name: Build & Install `furiosa-smi`
        shell: bash
        run: |
          cd furiosa-smi
          cargo build
          make install

      - name: Run `sudo ldconfig`
        shell: bash
        run: |
          sudo ldconfig

      - name: Checkout this project
        uses: actions/checkout@v4

      - name: Set GitHub credentials
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Install rust components
        run: rustup component add clippy rustfmt
      - name: install cargo tools
        run: cargo install --force cargo-sort # cargo-machete
      - name: sort
        run: cargo sort --grouped --check --workspace
      - name: clippy
        run: cargo fmt --all --check && cargo -q clippy --all-targets -- -D rust_2018_idioms -D warnings
      - name: Run build
        run: cargo build
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: make test